### PR TITLE
updating `is.boolean` method

### PR DESCRIPTION
**Pull request by KhaledElAnsari**
According to [this comment](https://github.com/sindresorhus/is/pull/12#issuecomment-334327363) comparing variable to boolean values `true` and `false` manually is faster than using `typeof` so I'm changing the function for a faster results

### CODE REVIEW

**Comment by gioragutt** [comment]
btw, @sindresorhus, do you have a source on that claim?,

also, @KhaledElAnsari, for consistency, remove the `( )` around `value`: `(value) => ...` => `value => ...`,
also, the CI failed, make sure to see what the failure report says.

**Comment by gioragutt** [comment]
Thanks @KhaledElAnsari !

**Comment by KhaledElAnsari** [comment]
no problem @gioragutt

**Comment by gioragutt** [comment]
@sindresorhus got it, sorry. I believe we can enforce that in the CI, I know that `@angular/cli` does that.

**Comment by sindresorhus** [comment]
@gioragutt No worries. I forgot to tell you. I don't want to enforce it as nobody follows that. I've tried many times before. Just easier for us to rename the PR and squash merge.

**Comment by sindresorhus** [comment]
> btw, @sindresorhus, do you have a source on that claim?,

I benchmarked it a year ago and then it was faster.

**Comment by gioragutt** [comment]
@sindresorhus cool. I'll know from now on.

**Pull request merged**
