### PR TITLE
boolean can be detected with `typeof`

### PR DESCRIPTION
**Pull request by KhaledElAnsari**
according to mdn `typeof` return string boolean for the boolean type (`true` and `false`)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof

### CODE REVIEW

**Comment by sindresorhus** [comment]
I’m aware, but using true and false was intentional. It’s slightly faster.

**Comment by gioragutt** [comment]
@sindresorhus if so, shouldn't `is.boolean` be `val => val === true || val === false`?

**Comment by sindresorhus** [comment]
Yes

**Comment by KhaledElAnsari** [comment]
good point @gioragutt

**Comment by gioragutt** [comment]
@KhaledElAnsari mind changing that in a PR?

**Pull request closed without merging**
