### PR TITLE
Add `is.truthy()` and `is.falsy()`

### PR DESCRIPTION
**Pull request by brandon93s**

### CODE REVIEW

**Comment by gioragutt** [comment]
Thanks man! Nice and clean PR.

**Comment by sindresorhus** [comment]
@brandon93s Would you be interested in joining the project? No worries if not.

**Comment by brandon93s** [comment]
@sindresorhus Absolutely, I would be delighted! 😄

**Comment by sindresorhus** [comment]
Awesome. Welcome :)

**Pull request merged**
